Adding __eq__ method to KeyJar
Catch Exceptions correctly

Close #313

Add change log entry for #313.

In Python 2.7, this conversion to `newstr` triggers:
 AttributeError: 'newstr' object has no attribute 'items'

Decrease complexity of oic/utils/authn/saml.py

Importing oic.utils.authn.saml without saml2 raises ImportError

In Python 2.7, this conversion to `newstr` triggers:
 AttributeError: 'newstr' object has no attribute 'items'

Remove if/else, just return.

Fix sanitize to completely replace strings starting with B or U

Fix #287

Add test coverage to CI, Integrate with coveralls, add badge

Moved sector_identifier checks outside

A new IdP example based on op2.

Remove some comments.

Refine claims_match to essential functionality.

From what I can gather from usage and implementation, this
function does not really want to check `value/values`, but
only cares about equality or presence.

Fix python 3 input syntax for python 2 support
In PR #117 commit 4e1ae5ab8a889b57a59f9c5d9ecf6df04fdaaf4f breaks the client_management module under Python 2 because of the change of the input builtin in Python 3

Clean up lazy logging and remove comments.